# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  snmp_settings:
    type: dict
    description: Set SNMP settings. It is optional
    keys:
      contact:
        type: str
        description: Contact info
      location:
        type: bool
        default: false
        description: Formatted as {{ fabric_name }} {{ dc_name }} {{ pod_name }} {{ switch_rack }} {{ inventory_hostname }}
      compute_local_engineid:
        type: bool
        default: false
        description: |
          Generate a local engineId for SNMP by hashing via SHA1 the string
          generated via the concatenation of the hostname plus the management IP.
          {{ inventory_hostname }} + {{ switch.mgmt_ip }}
      compute_v3_user_localized_key:
        type: bool
        default: false
        description: |
          Requires compute_local_engineid to be `true` if enabled, the SNMPv3
          passphrases for auth and priv are transfromed using RFC 2574,
          matching the value they would take in EOS cli the algorithm requires
          a local engineId which is unknown to AVD hence the necessity to generate
          one beforehand.
      users:
        type: list
        items:
          type: dict
          keys:
            name:
              type: str
              description: Username
            group:
              type: str
            version:
              type: str
              valid_values: ["v1", "v2c", "v3"]
            auth:
              type: str
              valid_values: ["md5", "sha", "sha256", "sha384", "sha512"]
            auth_passphrase:
              type: str
              required: true
              description: Clear passphrase. Recommended to use vault
            priv:
              type: str
              valid_values: ["des", "aes", "aes192", "aes256"]
            priv_passphrase:
              type: str
              required: true
              description: Clear passphrase. Recommended to use vault
