# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  svi_profiles:
    type: list
    description: |
      Optional profiles to apply on SVI interfaces \
      Each profile can support all or some of the following keys according to your own needs. \
      Keys are the same used under SVI. \
      Svi_profiles can refer to another svi_profiles to inherit settings in up to two levels (svi->profile->parent_profile).  
    items:
      type: dict
      keys:
        profile:
          type: str
        parent_profile:
          type: str
        mtu:
          type: int
        enabled:
          type: bool
        ip_virtual_router_addresses:
          type: list
          items:
            type: str
        ip_address_virtual:
          type: str
        ip_address_virtual_secondaries:
          type: list
          items:
            type: str
        igmp_snooping_enabled:
          type: bool
          default: true
        ip_helpers:
          type: list
          items:
            type: dict
            keys:
              ip_helper:
                type: str
              source_interface:
                type: str
              source_vrf:
                type: str
