# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  tenants:
    type: list
    items:
      type: dict
      keys:
        name:
          type: str
        pseudowire_rt_base:
          type: int
          description: Pseudowire rt base, used to generate route targets for vpws services. Avoid overlapping route target spaces between different services.
        point_to_point_services:
          type: list
          description: Define point to point services (pseudowires) as a list of dictionaries.
          items:
            type: dict
            keys:
              name:
                type: str
                description: L1 service pseudowire name
              type:
                type: str
                description: L1 service type, currently only vpws-pseudowire is supported.
              subinterfaces:
                type: list
                description: Subinterfaces will create subinterfaces and additional pseudowires/patch panel config
                items:
                  type: dict
                  keys:
                    number:
                      type: str
              endpoints:
                type: list
                description: Pseudowire terminating endpoints.
                items:
                  type: dict
                  keys:
                    id:
                      type: int
                      required: true
                    nodes: 
                      type: list
                      description: With ESI multihoming we support 2 nodes per pseudowire endpoint
                      items:
                        type: str
                    interfaces:
                      type: list
                      description: Interfaces patched to the pseudowire on side
                      items:
                        type: str
                    port_channel:
                      type: dict
                      keys:
                        mode:
                          type: str
                        short_esi:
                          type: str
              lldp_disable:
                type: bool
                description: Whether to disable lldp rx/tx on port mode pseudowire services
