hostname: port-channel-short-esi
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ip_igmp_snooping:
  globally_enabled: true
ethernet_interfaces:
- name: Ethernet10
  peer: server01_ESI
  peer_interface: Eth1
  peer_type: server
  port_profile: TENANT_A_B
  description: server01_ESI_Eth1
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 10
    mode: active
port_channel_interfaces:
- name: Port-Channel10
  description: server01_ESI_PortChanne1
  type: switched
  shutdown: false
