hostname: port-channel-short-esi
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ip_igmp_snooping:
  globally_enabled: true
ethernet_interfaces:
- name: Ethernet10
  peer: server01_ESI
  peer_interface: Eth1
  peer_type: server
  port_profile: TENANT_A_B
  description: server01_ESI_Eth1
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 10
    mode: active
- name: Ethernet12
  peer: server01_ESI
  peer_interface: Eth6
  peer_type: server
  description: server01_ESI_Eth6
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 12
    mode: active
port_channel_interfaces:
- name: Port-Channel10
  description: server01_ESI_PortChanne1
  type: switched
  shutdown: false
  evpn_ethernet_segment:
    identifier: 0000:0000:0303:0202:0101
    route_target: 03:03:02:02:01:01
  lacp_id: 0303.0202.0101
- name: Port-Channel12
  description: server01_ESI_PortChanne1
  type: switched
  shutdown: false
  mtu: 1601
  evpn_ethernet_segment:
    identifier: 0000:0000:0303:0202:0102
    route_target: 03:03:02:02:01:02
  lacp_id: 0303.0202.0102
