# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  cvx:
    type: dict
    keys:
      shutdown:
        type: bool
      services:
        type: dict
        keys:
          mcs:
            type: dict
            keys:
              redis:
                type: dict
                keys:
                  password:
                    type: str
                  password_type:
                    type: str
                    convert_types:
                      - int
                    valid_values: ["0", "7", "8a"]
                    default: "7"
              shutdown:
                type: bool
