# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  dynamic_prefix_lists:
    type: list
    items:
      type: dict
      keys:
        name:
          type: str
          display_name: Dynamic Prefix List Name
        match_map:
          type: str
          display_name: Route Map
        prefix_list:
          type: dict
          keys:
            ipv4:
              type: str
              display_name: IPv4 Prefix List
            ipv6:
              type: str
              display_name: IPv6 Prefix List
