# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  hardware_counters:
    type: dict
    keys:
      features:
        type: list
        secondary_key: direction
        primary_key: name
        convert_types:
          - dict
        items:
          type: dict
          keys:
            name:
              type: str
              required: true
              display_name: Name of the feature
            direction:
              type: str
              required: true
              valid_values: ["in", "out"]
