# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  platform:
    type: dict
    keys:
      trident:
        type: dict
        keys:
          forwarding_table_partition:
            type: str
      sand:
        type: dict
        description: Most of the platform sand options are hardware dependant and optional
        keys:
          qos_maps:
            type: list
            display_name: QOS Maps
            items:
              type: dict
              keys:
                traffic_class:
                  type: int
                  description: 0-7
                to_network_qos:
                  type: int
                  display_name: To Network QOS
                  description: 0-63
          lag:
            type: dict
            display_name: LAG
            keys:
              hardware_only:
                type: bool
              mode:
                type: str
          forwarding_mode:
            type: str
          multicast_replication:
            type: dict
            keys:
              default:
                type: str
                valid_values: ["ingress", "egress"]
