# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  policy_maps:
    type: dict
    display_name: QOS Policy-map
    keys:
      pbr:
        type: list
        primary_key: name
        convert_types:
          - dict
        items:
          type: dict
          keys:
            name:
              type: str
              display_name: Policy-Map Name
            classes:
              type: list
              primary_key: name
              convert_types:
                - dict
              items:
                type: dict
                keys:
                  name:
                    type: str
                    display_name: Class Name
                  index:
                    type: int
                    convert_types:
                      - str
                  drop:
                    description: Only one of "drop" and "set" can be set simultaneously
                    display_name: Drop Packets
                    type: bool
                  set:
                    description: Only one of "set" and "drop" can be set simultaneously
                    display_name: Set Values
                    type: dict
                    keys:
                      nexthop:
                        type: dict
                        keys:
                          ip_address:
                            type: str
                            description: IPv4_address | IPv6_address
                          recursive:
                            type: bool
      qos:
        type: list
        primary_key: name
        convert_types:
          - dict
        items:
          type: dict
          keys:
            name:
              type: str
              display_name: Policy-Map Name
            classes:
              type: list
              primary_key: name
              convert_types:
                - dict
              items:
                type: dict
                keys:
                  name:
                    type: str
                    display_name: Class Name
                  set:
                    type: dict
                    keys:
                      cos:
                        type: int
                        convert_types:
                          - str
                        display_name: COS-Value
                      dscp:
                        type: str
                        display_name: DSCP-Code
                      traffic_class:
                        type: int
                        convert_types:
                          - str
                        display_name: Traffic-class ID
                      drop_precedence:
                        type: int
                        convert_types:
                          - str
                        display_name: Drop-precedence Value
