# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  roles:
    type: list
    items:
      type: dict
      keys:
        name:
          type: str
          display_name: Role Name
        sequence_numbers:
          type: list
          items:
            type: dict
            keys:
              sequence:
                type: int
                convert_types:
                  - str
                display_name: Sequence Number
              action:
                type: str
                valid_values: ["permit", "deny"]
              mode:
                type: str
                description: |
                  ["config", "config-all", "exec", mode]
                  Example: "config"
              command:
                type: str
                display_name: Command As String
