# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  route_maps:
    type: list
    primary_key: name
    convert_types:
      - dict
    display_name: Route Maps
    items:
      type: dict
      keys:
        name:
          type: str
          required: true
          display_name: Route-map Name
        sequence_numbers:
          type: list
          required: true
          primary_key: sequence
          convert_types:
            - dict
          items:
            type: dict
            keys:
              sequence:
                type: int
                required: true
                display_name: Sequence ID
                convert_types:
                  - str
              type:
                type: str
                required: true
                valid_values: [ "permit", "deny" ]
              description:
                type: str
                display_name: Description
              match:
                type: list
                description: Match as a string
                items:
                  type: str
              set:
                type: list
                items:
                  type: str
              sub_route_map:
                type: str
                display_name: Sub-route name
              continue:
                type: dict
                keys:
                  enabled:
                    type: bool
                  sequence_number:
                    type: int
                    convert_types:
                      - str
