# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  vrfs:
    type: list
    display_name: VRF Instances
    primary_key: name
    convert_types:
      - dict
    items:
      type: dict
      keys:
        name:
          type: str
          display_name: VRF Name
        description:
          type: str
        ip_routing:
          type: bool
          display_name: IP Routing
        ipv6_routing:
          type: bool
          IPv6 Routing
        tenant:
          type: str
          description: Key only used for documentation or validation purposes
