---
all:
  children:
    EOS_DESIGNS_FAILURES:
      hosts:
        failure-port-channel:
        duplicate-network-port:
        duplicate-interface-l3-edge:
        duplicate-vlans:
        duplicate-vrfs:
        duplicate-vrfs-same-tenant:
        duplicate-l3-interfaces-network-services:
        duplicate-interfaces-point-to-point-services:
        duplicate-interfaces-in-point-to-point-services:
        duplicate-interfaces-connected-endpoints:
        duplicate-interfaces-core-interfaces:
        duplicate-interfaces-core-interfaces-with-port-channel:
        duplicate-vni-vxlan-interface:
        duplicate-vni-l3-interfaces-in-vxlan-interface:
        duplicate-vni-l2vlans-vxlan-interface:
        duplicate-interfaces-underlay:
        duplicate-sub-interfaces-point-to-point-services:
        duplicate-interface-name-in-sub-interfaces-point-to-point-services:
