---
all:
  children:
    EOS_DESIGNS_FAILURES:
      hosts:
        failure-port-channel:
        duplicate-network-port:
        duplicate-interface-l3-edge:
        duplicate-vlans:
        duplicate-vrfs:
        duplicate-vrfs-same-tenant:
