router_bgp:
  as: '101'
  router_id: 192.168.255.109
  bgp_defaults:
  - maximum-paths 4 ecmp 4
  peer_groups:
    IPv4-UNDERLAY-PEERS:
      type: ipv4
      maximum_routes: 12000
      send_community: all
    EVPN-OVERLAY-PEERS:
      type: evpn
      update_source: Loopback0
      bfd: true
      send_community: all
      maximum_routes: 0
      ebgp_multihop: 3
  address_family_ipv4:
    peer_groups:
      IPv4-UNDERLAY-PEERS:
        activate: true
      EVPN-OVERLAY-PEERS:
        activate: false
  redistribute_routes:
    connected:
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: true
  vlans:
    110:
      tenant: MY_FABRIC
      rd: 192.168.255.109:10110
      route_targets:
        both:
        - 10110:10110
      redistribute_routes:
      - learned
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
  MGMT:
    ip_routing: false
management_api_http:
  enable_vrfs:
    MGMT: {}
  enable_https: true
loopback_interfaces:
  Loopback0:
    description: EVPN_Overlay_Peering
    shutdown: false
    ip_address: 192.168.255.109/32
  Loopback1:
    description: VTEP_VXLAN_Tunnel_Source
    shutdown: false
    ip_address: 192.168.254.109/32
prefix_lists:
  PL-LOOPBACKS-EVPN-OVERLAY:
    sequence_numbers:
      10:
        action: permit 192.168.255.0/24 eq 32
      20:
        action: permit 192.168.254.0/24 eq 32
route_maps:
  RM-CONN-2-BGP:
    sequence_numbers:
      10:
        type: permit
        match:
        - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
vlans:
  110:
    tenant: MY_FABRIC
    name: SVI-110
ip_igmp_snooping:
  globally_enabled: true
ip_virtual_router_mac_address: 00:dc:00:00:00:0a
vlan_interfaces:
  Vlan110:
    tenant: MY_FABRIC
    description: SVI-110
    shutdown: false
    ip_address_virtual: 10.1.10.1
vxlan_interface:
  Vxlan1:
    description: evpn-vtep-with-default-vrf-not-evpn_VTEP
    vxlan:
      udp_port: 4789
      source_interface: Loopback1
      vlans:
        110:
          vni: 10110
