---
node_type_keys:
  pe:
    type: pe
    mpls_lsr: true
    default_mpls_overlay_role: client
    default_evpn_role: client
    network_services:
      l1: true
      l2: true
      l3: true
    default_overlay_routing_protocol: ibgp
    default_overlay_address_families: [ evpn ]
    default_evpn_encapsulation: mpls

pe:
  defaults:
    loopback_ipv4_pool: 10.42.0.0/24
    bgp_as: 42
  nodes:
    duplicate-l3-interfaces-network-services:
      id: 42

type: pe
design:
  type: mpls

tenants:
  - name: TENANT_B
    pseudowire_rt_base: 2000
    mac_vrf_id_base: 20000
    vrfs:
      - name: TENANT_B_WAN
        vrf_id: 20
        address_families:
          - vpn-ipv4
          - vpn-ipv6
        ospf:
          enabled: true
          process_id: 99
          router_id: 192.168.48.4
          max_lsa: 10000
          nodes:
            - duplicate-l3-interfaces-network-services
        l3_interfaces:
          - description: TENANT_B_SITE_3_OSPF
            enabled: true
            interfaces:
              - Ethernet6.101
            ip_addresses:
              - 192.168.48.4/31
            nodes:
              - duplicate-l3-interfaces-network-services
            ospf:
              enabled: true
              point_to_point: true
              area: 0
              cost: 10
          - description: TENANT_B_SITE_5
            enabled: true
            interfaces:
              - Ethernet6.101
            ip_addresses:
              - 192.168.48.2/31
            nodes:
              - duplicate-l3-interfaces-network-services

expected_error_message: "Duplicate interface_name Ethernet6.101 found while generating l3_interfaces under network_services vrf: TENANT_B_WAN. Description on duplicate interface: TENANT_B_SITE_3_OSPF"
