---
# Minimum config to only test the specific feature.
node_type_keys:
  pe:
    type: pe
    mpls_lsr: true
    default_mpls_overlay_role: client
    default_evpn_role: client
    network_services:
      l1: true
      l2: true
      l3: true
    default_overlay_routing_protocol: ibgp
    default_overlay_address_families: [ evpn ]
    default_evpn_encapsulation: mpls

pe:
  defaults:
    loopback_ipv4_pool: 10.42.0.0/24
    bgp_as: 42
  nodes:
    duplicate-interfaces-point-to-point-services:
      id: 42

type: pe
design:
  type: mpls

tenants:
  - name: TENANT_B
    vrfs:
      - name: TENANT_B_WAN
        vrf_id: 20
        l3_interfaces:
          - description: TENANT_B_SITE_3_OSPF
            enabled: true
            interfaces:
              - Ethernet6
            ip_addresses:
              - 192.168.48.4/31
            nodes:
              - duplicate-interfaces-point-to-point-services
            ospf:
              enabled: true
              point_to_point: true
              area: 0
              cost: 10
    point_to_point_services:
      - name: TEN_A_site2_site5_eline_port_based
        endpoints:
          - id: 26
            nodes: [ "duplicate-interfaces-point-to-point-services" ]
            # duplicate interface
            interfaces: [ "Ethernet6" ]
            port_channel:
              description: Description1
              mode: active

expected_error_message: "Duplicate interface_name Ethernet6 found while generating ethernet_interfaces for point_to_point_services node: duplicate-interfaces-point-to-point-services"
