type: dict
allow_other_keys: true
keys:
  prefix_lists:
    type: list
    primary_key: name
    convert_types:
    - dict
    display_name: Prefix Lists
    items:
      type: dict
      keys:
        name:
          type: str
          required: true
          display_name: prefix_litss_name
        sequence_numbers:
          type: list
          required: true
          primary_key: sequence
          convert_types:
          - dict
          items:
            type: dict
            keys:
              sequence:
                type: int
                required: true
                display_name: Sequence ID
                convert_types:
                - str
              action:
                type: str
                required: true
                display_name: action as string
